# Generated by Django 4.2.4 on 2023-11-08 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_nacionalidad', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.TextField(max_length=15)),
                ('password_usuario', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apoderado_rut', models.TextField(max_length=20)),
                ('apoderado_nombres', models.TextField(max_length=100)),
                ('apoderado_paterno', models.TextField(max_length=100)),
                ('apoderado_materno', models.TextField(max_length=100)),
                ('apoderado_edad', models.PositiveIntegerField()),
                ('apoderado_parentesco', models.TextField(max_length=100)),
                ('estudiante_rut', models.TextField(max_length=20)),
                ('estudiante_nombres', models.TextField(max_length=100)),
                ('estudiante_paterno', models.TextField(max_length=100)),
                ('estudiante_materno', models.TextField(max_length=100)),
                ('estudiante_edad', models.PositiveIntegerField()),
                ('apoderado_nacionalidades', models.ManyToManyField(related_name='matriculas_apoderados', to='gestion.nacionalidad')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
                ('estudiante_nacionalidades', models.ManyToManyField(related_name='matriculas_estudiantes', to='gestion.nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.TextField(max_length=200)),
                ('tabla_afectada_historial', models.TextField(max_length=100)),
                ('fecha_hora', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.TextField(max_length=20)),
                ('nombres', models.TextField(max_length=100)),
                ('paterno', models.TextField(max_length=100)),
                ('materno', models.TextField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('cargo', models.TextField(max_length=100)),
                ('asignaturas', models.TextField(max_length=200)),
                ('cursos', models.ManyToManyField(blank=True, related_name='funcionarios', to='gestion.curso')),
                ('jefatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
            ],
        ),
    ]
