# Generated by Django 4.2.7 on 2023-11-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_rename_accion_historial_descripcion_historial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='jefatura',
            field=models.TextField(max_length=200),
        ),
    ]
