# Generated by Django 4.2.7 on 2023-11-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_funcionario_jefatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_asignatura', models.TextField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='jefatura',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='jefatura_cursos',
            field=models.ManyToManyField(blank=True, related_name='jefes', to='gestion.curso'),
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='asignaturas',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='funcionarios', to='gestion.asignatura'),
        ),
    ]
