# Generated by Django 4.2.7 on 2023-11-22 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_funcionario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
