# Generated by Django 4.2.4 on 2023-11-29 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_rename_cursos_matricula_curso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='jefatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jefatura', to='gestion.curso'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='gestion.curso'),
        ),
    ]
